###Garden 1

### Add a garden 1
POST http://localhost:8080/api/gardens
Content-Type: application/json

{
    "gardenName":"Garden 1"
}

### Add a zone 1 to garden 1
POST http://localhost:8080/api/gardens/1/zones
Content-Type: application/json

{
    "gardenZoneName":"Zone 1 in garden 1"
}

### Add a plant 1 to zone 1 in garden 1
POST http://localhost:8080/api/gardens/1/zones/1/plants
Content-Type: application/json

{
    "plantName":"Plant 1 in zone 1 in garden 1"
}

### Get latest tracker event
GET http://localhost:8080/api/gardens/1/zones/1/plants/1/tracker/WATER/latest

### Get latest garden zone tracker event
GET http://localhost:8080/api/gardens/1/zones/1/tracker/TEST_SOIL_MOISTURE/latest

### Record a plant tracker event
POST http://localhost:8080/api/gardens/1/zones/1/plants/1/tracker
Content-Type: application/json

{
    "plantTrackerEventType":"PEST_TREATMENT",
    "details":"3: I pest treateded my plant!!!"
}

### Record another plant tracker event
POST http://localhost:8080/api/gardens/1/zones/1/plants/1/tracker
Content-Type: application/json

{
    "plantTrackerEventType":"WATER",
    "details":"2: I watered my plant!!!"
}

### Record 1 garden zone tracker event
POST http://localhost:8080/api/gardens/1/zones/1/tracker
Content-Type: application/json

{
    "gardenZoneTrackerEventType":"TEST_SOIL_MOISTURE",
    "details":"1: I tested my soil moisture."
}

### Record 2 garden zone tracker event
POST http://localhost:8080/api/gardens/1/zones/1/tracker
Content-Type: application/json

{
    "gardenZoneTrackerEventType":"TEST_SOIL_PH",
    "details":"2: I tested my soil pH."
}

### Record 3 garden zone tracker event
POST http://localhost:8080/api/gardens/1/zones/1/tracker
Content-Type: application/json

{
    "gardenZoneTrackerEventType":"WEED",
    "details":"3: i weeded my garden zone."
}

### Record a garden zone tracker event
POST http://localhost:8080/api/gardens/1/zones/1/tracker
Content-Type: application/json

{
    "gardenZoneTrackerEventType":"TEST_SOIL_MOISTURE",
    "details":"I tested my soil moisture again."
}




###Garden 2

### Add a garden 2
POST http://localhost:8080/api/gardens
Content-Type: application/json

{
    "gardenName":"Garden 2"
}

### Add a zone 1 to garden 2
POST http://localhost:8080/api/gardens/2/zones
Content-Type: application/json

{
    "gardenZoneName":"Zone 1 in garden 2"
}

### Add a plant 1 to zone 1 in garden 2
POST http://localhost:8080/api/gardens/2/zones/2/plants
Content-Type: application/json

{
    "plantName":"Plant 1 in zone 1 in garden 2"
}
